import{a as v,S as R,i}from"./assets/vendor-DQvd0HNi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const S="https://pixabay.com/api/",q="55159372-d264c9d22d658374374c360aa",m=15;let u=0;async function h(e,o){const s=await v.get(S,{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:m}}),a=s.data.totalHits;return u=Math.ceil(a/m),s.data}const f=document.querySelector(".gallery"),y=document.querySelector(".loader"),d=document.querySelector(".load-more"),B=new R(".gallery a",{});function $(e){return`<li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <ul class="stats">
        <li class="stats-item"><p class="stat-title">likes</p><p class="stat-value">${e.likes}</p></li>
        <li class="stats-item"><p class="stat-title">views</p><p class="stat-value">${e.views}</p></li>
        <li class="stats-item"><p class="stat-title">comments</p><p class="stat-value">${e.comments}</p></li>
        <li class="stats-item"><p class="stat-title">downloads</p><p class="stat-value">${e.downloads}</p></li>   
      </ul>
    </li>`}function g(e){const o=e.map($).join("");f.insertAdjacentHTML("beforeend",o),B.refresh()}function A(){f.innerHTML=""}function w(){y.style.display="block"}function L(){y.style.display="none"}function P(){d.style.display="block"}function c(){d.style.display="none"}const p=document.querySelector(".form");let b="",n=1;p.addEventListener("submit",M);d.addEventListener("click",T);function M(e){e.preventDefault(),n=1;const s=new FormData(e.target).get("search-text").trim();if(s===""||s===void 0){i.show({position:"topRight",backgroundColor:"red",message:"Введіть текст для пошуку"});return}b=s,w(),A(),c(),setTimeout(async()=>{try{const t=(await h(s,n)).hits;if(t.length===0){i.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(t),P(),n++}catch(a){i.show({message:`Error: ${a}`,color:"red",position:"topRight"})}finally{if(L(),p.reset(),n>=u)return c(),i.error({position:"topRight",message:"We're sorry, there are no more posts to load"})}},200)}function T(){if(n+=1,c(),n>=u)return i.error({position:"topRight",message:"We're sorry, there are no more posts to load"});w(),setTimeout(async()=>{try{const o=(await h(b,n)).hits;if(o.length===0){i.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(o),P()}catch(e){i.show({message:`Error: ${e}`,color:"red",position:"topRight"})}finally{x(),L(),p.reset()}},200)}function x(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
