import{a as v,S,i as n}from"./assets/vendor-DQvd0HNi.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const R="https://pixabay.com/api/",$="55159372-d264c9d22d658374374c360aa",d=15;let p=0;async function m(e,s){const r=await v.get(R,{params:{key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:d}}),a=r.data.totalHits;return p=Math.ceil(a/d),r.data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),c=document.querySelector(".load-more"),q=new S(".gallery a",{});function A(e){return`<li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <ul class="stats">
        <li class="stats-item"><p class="stat-title">likes</p><p class="stat-value">${e.likes}</p></li>
        <li class="stats-item"><p class="stat-title">views</p><p class="stat-value">${e.views}</p></li>
        <li class="stats-item"><p class="stat-title">comments</p><p class="stat-value">${e.comments}</p></li>
        <li class="stats-item"><p class="stat-title">downloads</p><p class="stat-value">${e.downloads}</p></li>   
      </ul>
    </li>`}function y(e){const s=e.map(A).join("");f.insertAdjacentHTML("beforeend",s),q.refresh()}function M(){f.innerHTML=""}function g(){h.style.display="block"}function w(){h.style.display="none"}function L(){c.style.display="block"}function P(){c.style.display="none"}const u=document.querySelector(".form");let b="",i=1;u.addEventListener("submit",T);c.addEventListener("click",x);function T(e){e.preventDefault(),i=1;const r=new FormData(e.target).get("search-text").trim();if(r===""||r===void 0){n.show({position:"topRight",backgroundColor:"red",message:"Введіть текст для пошуку"});return}b=r,g(),M(),P(),setTimeout(async()=>{try{const t=(await m(r,i)).hits;if(t.length===0){n.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t),L(),i++}catch(a){n.show({message:`Error: ${a}`,color:"red",position:"topRight"})}finally{w(),u.reset()}},200)}function x(){if(i+=1,P(),i>p)return n.error({position:"topRight",message:"We're sorry, there are no more posts to load"});g(),setTimeout(async()=>{try{const s=(await m(b,i)).hits;if(s.length===0){n.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(s),L(),i++}catch(e){n.show({message:`Error: ${e}`,color:"red",position:"topRight"})}finally{w(),u.reset()}},200),result}
//# sourceMappingURL=index.js.map
